name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up SonarQube scanner
      uses: SonarSource/sonarqube-scan-action@v4
      with:
        args: |
          -Dsonar.projectKey=TestingGithubSonarQube
          -Dsonar.sources=.
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Run SonarQube Scan
      run: |
        sonar-scanner.bat
