name: CI

on:
  push:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Listar archivos para depuración
        run: Get-ChildItem -Recurse

      - name: Verificar si el archivo de script existe
        run: |
          if (Test-Path -Path ".\scripts\install-sonar-scanner-cli.sh") {
            Write-Host "El archivo está presente."
          } else {
            Write-Host "El archivo no se encuentra."
          }

      - name: Instalar Sonar Scanner CLI
        run: .\scripts\install-sonar-scanner-cli.sh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          INPUT_SCANNERVERSION: 6.2.1.4610
          INPUT_SCANNERBINARIESURL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli

      - name: Ejecutar análisis de SonarQube
        run: |
          sonar-scanner -Dsonar.projectKey=mi_proyecto -Dsonar.sources=src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
